name = "lingering-butterfly-8295"
compatibility_date = "2026-02-08"

[env.production]
route = "https://mossel.cloud/*"
zone_id = ""

[[env.production.routes]]
pattern = "mossel.cloud/contact"
methods = ["POST"]

[assets]
directory = "./"

[build]
command = "npm install"
cwd = "./"